# Generated by Django 4.2.23 on 2025-07-25 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_course_updated_at_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
